name: Release

permissions:
  contents: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Sync version with tag
      run: |
        VERSION="${GITHUB_REF#refs/tags/}"
        VERSION="${VERSION#v}"
        npm pkg set version="$VERSION"

    - name: Compile TypeScript
      run: npm run compile

    - name: Set output file name
      run: echo "VSIX_FILE=$(npm pkg get name | tr -d '\"')-$(npm pkg get version | tr -d '\"').vsix" >> $GITHUB_ENV

    - name: Set prerelease flag
      run: |
        if [ "${{ github.event.release.prerelease }}" = "true" ]; then
          echo "VSCE_FLAGS=--pre-release" >> "$GITHUB_ENV"
        fi

    - name: Package extension
      run: npx vsce package $VSCE_FLAGS --out $VSIX_FILE

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.VSIX_FILE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

